version: "3.5"
services:

  mysql:
    image: mysql:8.0
    container_name: balshop_mysql
    restart: unless-stopped
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ALLOW_EMPTY_PASSWORD
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "${PHPMYADMIN_PORT:-8181}:80"
    environment:
      PMA_HOST: mysql

  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php
    restart: unless-stopped
    volumes:
      - .:/var/www/balshop.com
    ports:
      - "${PHP_PORT:-8000}:8000"
    depends_on:
      - mysql

  nginx:
    image: nginx:1.25.5
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./docker/nginx/balshop.com.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/balshop.com
    depends_on:
      - php

volumes:
  mysql_data:
